add bike
WildCodeSchool/orleans-php-202009-project-dfj-location pull request #123
Opened 2020-11-13 21:44 UTC by bloic

2020-11-15 12:41 UTC, Gambino-stack commented on src/Model/AdminBicycleManager.php
> +        $statement->bindValue('weight', $bike['weight']);
tu n'as pas mis les "\PDO::PARAM" sur deux champs

2020-11-15 12:42 UTC, Gambino-stack commented on src/View/Admin/add-bike.html.twig
> +                <input type="text" class="form-control" id="name" name="name" placeholder="Nom" required>
il faut rajouter les values a la fin de chaque input pour remettre les valeurs quand il y a une erreur.

2020-11-15 14:53 UTC, Gambino-stack reviewed
ca m'as l'air good!

2020-11-16 11:16 UTC, sblondeau requested changes

2020-11-16 11:16 UTC, sblondeau commented on public/assets/css/style.css
> +    background-color: rgba(18, 24, 43, 0.65);
variable

2020-11-16 11:16 UTC, sblondeau commented on public/assets/css/style.css
> +    color: darkred;
variable 2 lignes

2020-11-16 11:16 UTC, sblondeau commented on src/Controller/AdminBicycleController.php
> +        if (!empty($bike['category_id'] === 'catégorie')) {
je comprends pas ce que tu veux faire avec cette ligne
tu fait un !empty sur un test d'égalité, qui te renvoies true ou false... et c'est quoi cette string "catégorie" ?

2020-11-16 11:16 UTC, sblondeau commented on src/Model/BicycleManager.php
>      protected const TABLE1 = 'category';
enlève et utilise plutot CategoryManager::TABLE

2020-11-16 11:16 UTC, sblondeau commented on src/View/Admin/bikes.html.twig
> +<h1 class="my-5 text-center"> Administrer les vélos </h1>
cette page ne devrait pas etre dans une US sur l'ajout de vélo

2020-11-16 18:43 UTC, bloic commented on src/Controller/AdminBicycleController.php
> +        if (!empty($bike['category_id'] === 'catégorie')) {
dans mon select j'ai déclarer une balise <option>catégorie</option> pour que s'il est sélectionner alors c'est comme si la le champs n'a pas été choisi du coup il faut qu'il sélectionne l'un des 4 autres catégories qui est dans le select.

2020-11-16 18:47 UTC, bloic commented on src/View/Admin/bikes.html.twig
> +<h1 class="my-5 text-center"> Administrer les vélos </h1>
J'ai pas toucher cette page c'est quand vendredi j'ai repris de ma branche DEV qu'il est apparu je ne l'ai pas ajouté à mon US :)

2020-11-16 18:48 UTC, bloic commented on src/Model/BicycleManager.php
>      protected const TABLE1 = 'category';
J'utilise la table bike pour ajouté des vélos je comprends pas pourquoi du coup pourquoi CategoryManager

2020-11-18 06:46 UTC, Gambino-stack commented on src/Controller/AdminBicycleController.php
> +
Espace en trop :)

2020-11-18 06:46 UTC, Gambino-stack commented on src/Controller/AdminBicycleController.php
> +
Espace en trop

2020-11-18 06:46 UTC, Gambino-stack commented on src/Controller/AdminBicycleController.php
> +use App\Model\CategoryManager;
Mets un espace entre les use

2020-11-18 09:08 UTC, Gambino-stack approved these changes

2020-11-18 09:48 UTC, sblondeau approved these changes

2020-11-18 09:48 UTC, merged