S04 us06 carousel
WildCodeSchool/orleans-php-202009-project-dfj-location pull request #127
Opened 2020-11-16 09:43 UTC by Gambino-stack

2020-11-16 10:17 UTC, bloic commented on public/assets/css/style.css
> +
Un saut de ligne en trop

2020-11-16 10:32 UTC, bloic approved these changes
ok pour moi

2020-11-16 19:49 UTC, sblondeau requested changes
vous avez vraiment besoin de toutes ces images ?
car pour un carousel 3 images c'est bien...
et sinon, la plupart font >200ko, donc à réduire !

2020-11-17 18:35 UTC, bloic approved these changes
sa me semble ok

2020-11-18 08:14 UTC, sblondeau requested changes
j'ai encore des images >200ko (et en plus les images n'ont pas l'ait d'être utilisées dans le code...), comme par ex famille1.jpg
il ne faut pas push des images qui ne sont pas utilisées

2020-11-18 09:12 UTC, bloic approved these changes
la taille des fichier sont ok et le code aussi

2020-11-18 09:41 UTC, sblondeau approved these changes

2020-11-18 09:41 UTC, merged