US34 ajout de durée et tarifs form résa
WildCodeSchool/orleans-php-202009-project-dfj-location pull request #129
Opened 2020-11-17 15:13 UTC by Aurelie-F

2020-11-17 15:52 UTC, Gambino-stack approved these changes
c'est nickel 👌

2020-11-18 08:25 UTC, sblondeau requested changes
à retravailler, je pense que ta modélisation de BDD est pas bonne à la base donc tout ce qui en découle est aussi à revoir ! courage ;-)
hésite pas à revenir vers moi si tu as des questions où si j'ai mal compris ce que tu voulais faire

2020-11-18 08:25 UTC, sblondeau commented on src/Model/PriceManager.php
> +    public const TABLE = 'prices';
au singulier les noms de table

2020-11-18 08:25 UTC, sblondeau commented on src/Model/DurationManager.php
> +    public const TWO_WEEKS = '2 semaines';
les ID_... ce sont des id en BDD ? si oui ça ne va pas car tu ne peux pas savoir quels seront les id de la BDD. Sur la bdd en prod par ex les id seront sans doute différent

2020-11-18 08:25 UTC, sblondeau commented on database_dfj.sql
> +CREATE TABLE `dfj_location`.`prices` (
si je comprend bien ce que tu veux faire, tu veux une table avec les durées possible, et pour chaque vélo, indiquer le prix pour chaque durée ? si c'est bien ça, c'est une many to many en price et bike, et prices est ta table intermédiaire.
donc dans price tu dois avoir un bike_id et un duration_id, et non un duration_id dans bike

2020-11-18 08:25 UTC, sblondeau commented on src/Controller/ReservationController.php
> +            ($data['duration'] == DurationManager::ID_HALF_DAY || $data['duration'] == DurationManager::ID_TWO_WEEKS)
non là tu pars sur des cas trop compliqués.
il faut plutot vérifié si dans ta table price, tu as une ligne pour ce vélo à cette durée précise, sinon tu as l'erreur.

2020-11-18 10:53 UTC, Gambino-stack approved these changes
👌

2020-11-18 12:35 UTC, sblondeau requested changes

2020-11-18 12:35 UTC, sblondeau commented on src/Model/CategoryManager.php
> +    public const ID_TANDEM = 3;
const à enlever

2020-11-18 14:03 UTC, Gambino-stack approved these changes

2020-11-18 15:25 UTC, sblondeau approved these changes

2020-11-18 15:25 UTC, merged