delete_category finished
WildCodeSchool/orleans-php-202009-project-dfj-location pull request #130
Opened 2020-11-17 16:01 UTC by AliNedjar

2020-11-18 09:05 UTC, Gambino-stack approved these changes

2020-11-18 10:10 UTC, sblondeau requested changes

2020-11-18 10:10 UTC, sblondeau commented on src/Controller/AdminCategoryController.php
> +        $error = $this->remove();
non c'est pas logique de passer par index() pour faire un remove() qui renverrai des errors...
ton form de remove toi envoyer direct vers remove() puis tu as ta redirection vers index. Donc pas la peine de l'appeler ici

2020-11-18 10:10 UTC, sblondeau commented on src/View/Admin/indexCategory.html.twig
> +                    <form action="" method="post">
si c'est ton form pour delete, tu doit aller vers AdminCategory/remove

2020-11-18 11:28 UTC, Gambino-stack approved these changes

2020-11-18 12:43 UTC, sblondeau commented on src/Controller/AdminCategoryController.php
> +        $error = $this->remove();
non corrigé

2020-11-23 08:29 UTC, Aurelie-F approved these changes
ça me parait ok

2020-11-23 09:01 UTC, sblondeau approved these changes

2020-11-23 09:01 UTC, merged