S04 us02 footer fix
WildCodeSchool/orleans-php-202009-project-dfj-location pull request #132
Opened 2020-11-18 09:28 UTC by AliNedjar

2020-11-18 10:49 UTC, Gambino-stack commented on public/assets/css/style.css
> +    color: black;
La couleur tu peux la mettre en variable

2020-11-18 11:27 UTC, Gambino-stack approved these changes

2020-11-18 12:44 UTC, sblondeau requested changes

2020-11-18 12:44 UTC, sblondeau commented on public/assets/css/style.css
> +    min-height: 72.7582292849vh;
pourquoi ???

2020-11-18 13:37 UTC, bloic approved these changes
ok pour moi

2020-11-18 13:40 UTC, sblondeau approved these changes

2020-11-23 08:36 UTC, Aurelie-F approved these changes
c'est ok

2020-11-23 16:00 UTC, merged