S04 us11 editiondevelo
WildCodeSchool/orleans-php-202009-project-dfj-location pull request #140
Opened 2020-11-18 11:21 UTC by bloic

2020-11-18 11:29 UTC, Gambino-stack commented
Tu as des conflits

2020-11-18 11:30 UTC, Gambino-stack approved these changes

2020-11-18 12:30 UTC, Gambino-stack approved these changes

2020-11-18 12:31 UTC, Gambino-stack commented
Ca passe pas le travis de GitHub

2020-11-18 13:47 UTC, Gambino-stack approved these changes

2020-11-18 15:27 UTC, sblondeau requested changes

2020-11-18 15:27 UTC, sblondeau commented on src/Controller/AdminBicycleController.php
> +        $error = $this->remove();
non ! voir avec Ali pour corriger ça

2020-11-23 15:41 UTC, AliNedjar approved these changes
Tout m'a l'air bon

2020-11-23 16:03 UTC, sblondeau approved these changes

2020-11-23 16:03 UTC, merged