finish detailbike
WildCodeSchool/orleans-php-202009-project-dfj-location pull request #153
Opened 2020-11-24 15:37 UTC by bloic

2020-11-24 16:06 UTC, AliNedjar approved these changes
ça m'a l'air ok

2020-11-24 16:11 UTC, sblondeau requested changes

2020-11-24 16:11 UTC, sblondeau commented on src/Controller/DetailController.php
> +        $bicycleManager = new BicycleManager();
tu instacies 2 fois ton BicycleManager

2020-11-24 18:55 UTC, AliNedjar approved these changes
ça m'a l'air Ok.

2020-11-24 22:11 UTC, Aurelie-F commented
J’avais pas vu mais pour moi, il ne fallait pas créer un DetailController : l’URL sera bicycle/show/1 (donc méthode show dans BicycleController) et non detail/index/1...

2020-11-25 07:57 UTC, sblondeau approved these changes

2020-11-25 07:57 UTC, merged