change the carousel
WildCodeSchool/orleans-php-202009-project-dfj-location pull request #182
Opened 2020-11-25 13:39 UTC by Gambino-stack

2020-11-25 13:42 UTC, AliNedjar approved these changes
Approuvé

2020-11-25 16:42 UTC, sblondeau requested changes

2020-11-25 16:42 UTC, sblondeau commented on public/assets/css/style.css
> +    -webkit-background-size: cover !important;
pas de !important !
pas besoin non plus de tous les prefix, juste background-size suffit

2020-11-25 16:42 UTC, sblondeau commented on public/assets/css/style.css
>      #carouselExampleCaptions .carousel-inner {
cette media query est elle nécessaire ? et pas de syle sur des id, mais sur des classes

2020-11-25 19:09 UTC, Gambino-stack commented on public/assets/css/style.css
> +    -webkit-background-size: cover !important;
J'ai enlevé les prefixes mais si j'enlève les "!important" ce me coupe les images donc je sais pas comment faire sans ces derniers

2020-11-25 19:10 UTC, Gambino-stack commented on public/assets/css/style.css
>      #carouselExampleCaptions .carousel-inner {
La media query permet de régler la hauteur des images sur mobiles sinon c'est un peu long sur la plupart des mobiles

2020-11-25 19:27 UTC, AliNedjar approved these changes
corrections faites

2020-11-26 08:09 UTC, sblondeau requested changes

2020-11-26 08:09 UTC, sblondeau commented on public/assets/css/style.css
> +    background-size: cover !important;
non les !important ne sont pas nécessaire
avec ton inspecteur, regarde le selecteur correspondant à ton carousel, et reprend le meme ici pour le surcharger

2020-11-26 09:42 UTC, AliNedjar approved these changes
les changements demandés sont fait

2020-11-26 09:43 UTC, sblondeau approved these changes

2020-11-26 12:38 UTC, AliNedjar approved these changes
changements sont fait

2020-11-26 12:58 UTC, merged