change a placeholder, issue#161
WildCodeSchool/orleans-php-202009-project-dfj-location pull request #187
Opened 2020-11-25 15:03 UTC by Gambino-stack

2020-11-25 15:03 UTC, AliNedjar approved these changes
C'est ok

2020-11-25 16:44 UTC, sblondeau requested changes

2020-11-25 16:44 UTC, sblondeau commented on src/View/Reservation/reservation.html.twig
> +            <input class="form-control" type="number" min="1" name="number" id="number" placeholder="Quantité" required value="{{ data.number }}" >
hum si ton type=number, ne mets pas une chaine en placeholder
je te rappelles que le placeholder est sensé fournir un exemple à l'utilisateur, donc le "1" qu'il y avait avant est plus logique. Au pire modifie le label "Nombre" par "Quantité" plutot

2020-11-25 19:29 UTC, AliNedjar approved these changes
modifs faites

2020-11-26 08:15 UTC, sblondeau requested changes

2020-11-26 08:15 UTC, sblondeau commented on src/View/Reservation/reservation.html.twig
> +            <input class="form-control" type="number" min="1" name="number" id="number" placeholder="Quantité" required value="{{ data.number }}" >
ton placeholder est tjs sur "Quantité" alors qu'il devrait etre à 1 (ou une autre valeur numérique pour example)

2020-11-26 08:57 UTC, AliNedjar approved these changes
C'est ok

2020-11-26 09:15 UTC, sblondeau approved these changes

2020-11-26 09:15 UTC, merged