S01 us04 map
WildCodeSchool/orleans-php-202009-project-dfj-location pull request #25
Opened 2020-10-28 13:09 UTC by bloic

2020-10-28 13:58 UTC, Flichyn requested changes
Pas mal de petites choses à revoir mais ce sera vite fait !

2020-10-28 13:58 UTC, Flichyn commented on public/assets/css/style.css
> +.contact  h2{
Il y a un espace supplémentaire non nécessaire ligne 23 et il manque un espace entre le h2 et {.

2020-10-28 13:58 UTC, Flichyn commented on public/assets/css/style.css
> +
Ligne vide inutile ligne 30.

2020-10-28 13:58 UTC, Flichyn commented on public/assets/css/style.css
> +.contact {
Il manque un saut à la ligne entre les lignes 31 et 32.

2020-10-28 13:58 UTC, Flichyn commented on public/assets/css/style.css
> +
Ligne vide inutile ligne 35 et il manque un espace entre ton display: et ton flex ligne 33.

2020-10-28 13:58 UTC, Flichyn commented on public/assets/css/style.css
> +
Ligne vide inutile ligne 44 et il manque un espace entre container-map et { ligne 38.

2020-10-28 13:58 UTC, Flichyn commented on public/assets/css/style.css
> +
Ligne vide inutile ligne 48.

2020-10-28 13:58 UTC, Flichyn commented on public/assets/css/style.css
> +        display: flex;
Il manque un espace entre (max-width: 600px) et { ligne 50.
Il manque un espace entre contact ligne 51.
Il manque un espace entre display: et flex ligne 52.
Il manque un saut à la ligne entre les lignes 54 et 55.

2020-10-28 13:58 UTC, Flichyn commented on public/assets/css/style.css
> +
Ligne vide inutile ligne 59.

2020-10-28 13:58 UTC, Flichyn commented on public/assets/css/style.css
> +
Ligne vide inutile ligne 61.

2020-10-28 13:58 UTC, Flichyn commented on src/View/Home/index.html.twig
> +
Lignes vides inutiles lignes 5 et 6.
Il faut retirer le h1 "Hello Wilder !".

2020-10-28 13:58 UTC, Flichyn commented on src/View/Home/index.html.twig
> +
Ligne vide inutile ligne 17.

2020-10-28 13:58 UTC, Flichyn commented on src/View/Home/index.html.twig
> +        </div>
Ton p ligne 9 et ta div ligne 10 ne sont pas des enfants d'h2, ils doivent être indentés au même niveau que ton h2.
Aussi, ton iframe ligne 11 se trouve sur plusieurs lignes (tu as dû sauter une ligne au niveau du mot "style", qui se trouve maintenant ligne 13).

Au niveau de ton p ligne 9, il est préférable d'écrire "Téléphone", et il y a un espace en trop à la fin, avant ta balise fermante.
Au niveau de ton p ligne 15, il faut mettre une majuscule à "Faubourg". Et personnellement je n'aurai pas mis Orléans tout en majuscule, mais plutôt écrire comme je viens de le faire, mais je ne sais pas s'il y a une véritable meilleure façon de faire.

2020-10-29 08:37 UTC, sblondeau commented
ne passe pas travis.

2020-11-10 10:48 UTC, closed without merging