[S01_US01] Made a navbar
WildCodeSchool/orleans-php-202009-project-dfj-location pull request #29
Opened 2020-10-29 22:42 UTC by Flichyn

2020-10-30 08:45 UTC, Gambino-stack commented
Ok

2020-10-30 08:55 UTC, sblondeau requested changes

2020-10-30 08:55 UTC, sblondeau commented on public/assets/css/style.css
> +    background-color: #8C9DB0;
variable CSS couleur !

2020-10-30 08:55 UTC, sblondeau commented on src/View/includes/_navbar.html.twig
> +                <a class="nav-link" href="../Home/index">Accueil<span class="sr-only">(current)</span></a>
le lien doit etre /home/index direct, pas besoin des ../

2020-10-30 08:55 UTC, sblondeau commented on src/View/includes/_navbar.html.twig
> +    <a class="navbar-brand" href="../Home/index"><img class="logo" src="../../../assets/images/logo.png"/></a>
le lien doit etre dire /assets/images... ça se fait par rapport au fichier public/index.php qui affiche ton template

2020-10-30 09:12 UTC, Flichyn commented
J'ai push les corrections !

2020-10-30 09:31 UTC, sblondeau approved these changes

2020-10-30 09:48 UTC, Gambino-stack commented
nickel

2020-10-30 10:02 UTC, Flichyn commented
Il fallait cliquer sur commit merge mais j'étais pas sûr que ce soit à moi de le faire, du coup ça n'avait pas sauvegardé mes modifications... Done !

2020-11-02 11:05 UTC, Aurelie-F reviewed
c'est ok

2020-11-02 22:50 UTC, sblondeau approved these changes

2020-11-02 22:50 UTC, merged