add form
WildCodeSchool/orleans-php-202009-project-dfj-location pull request #31
Opened 2020-10-30 09:36 UTC by Gambino-stack

2020-10-30 09:40 UTC, Flichyn approved these changes

2020-10-30 09:50 UTC, sblondeau requested changes

2020-10-30 09:50 UTC, sblondeau commented on src/Controller/ReservationController.php
> +        $data = array_map('trim', $_POST);
le array_map se fait après le $_SERVER['REQUEST_METHOD']

2020-10-30 09:50 UTC, sblondeau commented on src/View/Reservation/reservation.html.twig
> +        <select class="form-control" id="veloselect" name="veloselect">
je n'ai pas l'impression que s'il y a une erreur, la valeur choisie soit bien reprise dans le form

2020-10-30 09:50 UTC, sblondeau commented on src/View/Reservation/reservation.html.twig
> +        <select class="form-control" id="veloselect" name="veloselect">
par ailleurs toutes les infos ici doivent provenir d'une BDD, et donc pas etre en dur

2020-10-30 10:02 UTC, Gambino-stack commented on src/View/Reservation/reservation.html.twig
> +        <select class="form-control" id="veloselect" name="veloselect">
tu parles pour la partie "veloselect" seulement ?

2020-11-05 09:54 UTC, Aurelie-F commented on public/assets/css/style.css
> +    --light- : #e8ecf0;
t'as un tiret en trop après light... ^^

2020-11-05 09:56 UTC, Aurelie-F commented on src/Controller/ReservationController.php
> +            'data' => $data ?? [], 'bikes' => $bikes]);
pour moi, tu n'as pas besoin de mettre ?? [] si tu as déclaré tes tableaux avant le if

2020-11-05 09:56 UTC, Aurelie-F commented on src/Controller/ReservationController.php
> +        return $errors ?? [];
pareil ici

2020-11-05 10:57 UTC, Aurelie-F commented
ça m'a l'air ok

2020-11-05 12:41 UTC, Aurelie-F commented
modifications ok

2020-11-05 15:38 UTC, Aurelie-F commented
ajout ok

2020-11-05 16:21 UTC, sblondeau commented
passe pas travis

2020-11-06 13:47 UTC, Aurelie-F approved these changes
c'est ok

2020-11-09 08:21 UTC, sblondeau requested changes

2020-11-09 08:21 UTC, sblondeau commented on src/Model/BicycleManager.php
> +    protected const TABLE1 = 'category';
non pas TABLE1. Si tu veux vraiment récupérer la constante, elle existe déjà dans le categoryManager ! 
donc pas la peine de la crééer ici. Tu fais un CategoryManager::TABLE :-)

2020-11-09 08:21 UTC, sblondeau commented on public/assets/css/form.css
> +#submit{
évite les id pour styliser, créer des classes plutot

2020-11-09 08:21 UTC, sblondeau commented on src/Controller/ReservationController.php
> +            $errors[] = "Entrez votre nom s.v.p";
C'est un détail mais soit cohérent sur tes messages d'erreur.
Par exemple, ici je mettrai plutot "Le nom est obligatoire", "Le prénome est obligatoire"...

2020-11-09 08:21 UTC, sblondeau commented on src/View/Reservation/reservation.html.twig
> +                <option value="">Choisissez la durée</option>
non il faut que ce soit dynamique ça... si le tarif est différent pour chaque vélo, il faut que ça vienne de la BDD car tu ne sais pas à l'avance qu'elles seront les categories de vélo !
mais en fait je mettrai cette partie dans une autre US. Pour l'instant, gère une réservation sans durée. Et plus tard vous ajoutez cette notion de durée / prix.
Autre solution plus simple (mais moins réaliste), on peut imaginer que le prix est le meme pour tous les vélos, et là tu pourrais avoir une seule table pour les tarifs (mais ça doit quand meme etre une table administrable pour que l'admin puisse modifier ses prix

2020-11-09 17:43 UTC, AliNedjar approved these changes
les dernières modifications sont bonnes

2020-11-10 07:59 UTC, sblondeau requested changes

2020-11-10 07:59 UTC, sblondeau commented on src/Controller/ReservationController.php
> +        if (empty($data['lastname'])) {
tes validations ne sont pas exhaustives
il faut aussi valider que la longueur des strings ne depasse pas celle du VARCHAR de la table correspondante en BDD

2020-11-10 08:10 UTC, AliNedjar commented on public/assets/css/form.css
> +input{
espace requis pour le PSR

2020-11-10 08:32 UTC, AliNedjar requested changes

2020-11-10 08:32 UTC, AliNedjar commented on public/assets/css/form.css
> +input{
espace requis ligne 2 à l'accolade d'input pour le PSR

2020-11-10 08:32 UTC, AliNedjar commented on public/assets/css/form.css
> +
ligne vide inutile ligne 4

2020-11-10 08:32 UTC, AliNedjar commented on public/assets/css/form.css
> +label{
espace requis ligne 6 à l'accolade d'input pour le PSR

2020-11-10 08:32 UTC, AliNedjar commented on public/assets/css/form.css
> +}
ligne vide requise entre ligne 8 et 9 pour le PSR

2020-11-10 08:32 UTC, AliNedjar commented on public/assets/css/form.css
> +form{
espace requis ligne 9 à l'accolade form pour le PSR

2020-11-10 08:32 UTC, AliNedjar commented on public/assets/css/form.css
> +
ligne vide inutile ici ligne 13

2020-11-10 08:32 UTC, AliNedjar commented on public/assets/css/form.css
> +}
espace requis ligne entre ligne 13 et 14

2020-11-10 08:32 UTC, AliNedjar commented on public/assets/css/form.css
> +.form-control{
espace requis ligne 15 à l'accolade form control pour le PSR

2020-11-10 08:32 UTC, AliNedjar commented on public/assets/css/form.css
> +}
ligne vide requise entre ligne 17 et 18

2020-11-10 08:32 UTC, AliNedjar commented on public/assets/css/form.css
> +.form-star{
espace requis ligne 18 à l'accolade form-star pour le PSR

2020-11-10 08:32 UTC, AliNedjar commented on public/assets/css/form.css
> +}
ligne vide requise entre ligne 24 et 25

2020-11-10 08:32 UTC, AliNedjar commented on public/assets/css/form.css
> +.btn{
espace requis ligne 25 à l'accolade btn pour le PSR

2020-11-10 08:32 UTC, AliNedjar commented on public/assets/css/form.css
> +}
ligne vide requise entre ligne 31 et 32

2020-11-10 08:32 UTC, AliNedjar commented on public/assets/css/form.css
> +form button:hover{
espace requis ligne 32 à l'accolade form button pour le PSR

2020-11-10 08:32 UTC, AliNedjar commented on public/assets/css/form.css
> +}
ligne vide requise entre ligne 35 et 36

2020-11-10 08:32 UTC, AliNedjar commented on public/assets/css/form.css
> +.info-form{
espace requis ligne 36 à l'accolade form pour le PSR

2020-11-10 08:32 UTC, AliNedjar commented on public/assets/css/form.css
> +.error{
espace requis ligne 41 à l'accolade error pour le PSR

2020-11-10 08:32 UTC, AliNedjar commented on public/assets/css/form.css
> +}
ligne vide requise entre ligne 44 et 45

2020-11-10 08:32 UTC, AliNedjar commented on public/assets/css/form.css
> +.card-header{
espace requis ligne 45 à l'accolade card-header pour le PSR

2020-11-10 08:32 UTC, AliNedjar commented on public/assets/css/form.css
> +}
ligne vide requise entre ligne 48 et 49

2020-11-10 08:32 UTC, AliNedjar commented on public/assets/css/form.css
> +.card-footer{
espace requis ligne 49 à l'accolade card-footer pour le PSR

2020-11-10 08:32 UTC, AliNedjar commented on public/assets/css/form.css
> +}
ligne vide requise entre ligne 52 et 53

2020-11-10 08:32 UTC, AliNedjar commented on public/assets/css/form.css
> +.card-body{
espace requis ligne 53 à l'accolade card-body pour le PSR

2020-11-10 08:32 UTC, AliNedjar commented on public/assets/css/form.css
> +}
ligne vide requise entre ligne 56 et 57

2020-11-10 08:32 UTC, AliNedjar commented on public/assets/css/form.css
> +.btn-info{
espace requis ligne 57 à l'accolade btn-info pour le PSR

2020-11-10 08:32 UTC, AliNedjar commented on public/assets/css/form.css
> +}
ligne vide à la fin de l'accolade ligne 60

2020-11-10 08:32 UTC, AliNedjar commented on public/assets/css/style.css
> +
double ligne vide inutile ligne 29 et 30

2020-11-10 08:32 UTC, AliNedjar commented on public/assets/css/style.css
> +
ligne vide inutile ligne 10

2020-11-10 08:32 UTC, AliNedjar commented on src/Controller/BicycleController.php
> +
deux ligne vide inutile ligne 13 et 14, laisse en une seule

2020-11-10 08:32 UTC, AliNedjar commented on src/Controller/ReservationController.php
> +    }
espace requis entre ligne 38 et 39 pour le psr

2020-11-10 08:32 UTC, AliNedjar commented on src/Model/BicycleManager.php
> +
ligne vide inutile ligne 15

2020-11-10 08:32 UTC, AliNedjar commented on src/Model/ReservationManager.php
> +    }
ligne vide requise entre ligne 27 et 28

2020-11-10 08:32 UTC, AliNedjar commented on src/View/Reservation/reservation.html.twig
> +{% endblock %}
ligne vide requise ligne 71

2020-11-10 08:32 UTC, AliNedjar commented on src/View/Reservation/thanks.html.twig
> +{% endblock %}
ligne vide requise ligne 38

2020-11-10 09:20 UTC, Flichyn commented on src/Controller/ReservationController.php
> +            $errors[] = "le nom et le prenom ne doivent pas depasser 100 caractères";
N'oublie pas les accents sur les mots "prénom" et "dépasser" ;)

2020-11-10 15:14 UTC, sblondeau requested changes
je ne vois pas le corrections :/

2020-11-12 10:08 UTC, AliNedjar requested changes
Des changements à faire pour tout ce qui PSR

2020-11-12 10:49 UTC, AliNedjar approved these changes
les modifications sont faites

2020-11-12 10:49 UTC, AliNedjar commented on src/View/Reservation/thanks.html.twig
> +    {{ parent() }} | Merci pour votre reservation
'réservation'.

2020-11-12 10:49 UTC, AliNedjar commented on src/View/Reservation/reservation.html.twig
> +    <p class="form-star">* : 1 Journée - Dimanche et jours fériés retrait ou retour = 4€ supplémantaires.
'supplémentaire'

2020-11-12 10:49 UTC, AliNedjar commented on src/View/Reservation/reservation.html.twig
> +        Pour tout retrait la veille ou restitution le lendemain , il faudra vous acquitter
pas d'espace avant une virgule

2020-11-12 13:38 UTC, sblondeau approved these changes

2020-11-12 13:39 UTC, merged