Finished user story
WildCodeSchool/orleans-php-202009-project-dfj-location pull request #55
Opened 2020-11-04 15:27 UTC by Flichyn

2020-11-04 15:29 UTC, Aurelie-F commented on public/assets/css/style.css
> +
C'est déjà dans mon css et j'ai mis avec une classe .bikes pour ne pas faire ça sur toutes les cards si jamais :)

2020-11-04 15:32 UTC, Aurelie-F commented on src/View/Category/index.html.twig
> +        <div class="row pb-5">
du coup il manque la classe bikes

2020-11-04 15:57 UTC, Aurelie-F commented
c'est ok

2020-11-04 19:23 UTC, sblondeau approved these changes

2020-11-04 19:23 UTC, sblondeau requested changes

2020-11-04 19:23 UTC, sblondeau commented on src/View/Category/index.html.twig
> +                            <h4 class="card-title text-center align-middle">{{ category.name }}</h4>
tu passes du h1 au h4

2020-11-04 19:47 UTC, Flichyn commented on src/View/Category/index.html.twig
> +                            <h4 class="card-title text-center align-middle">{{ category.name }}</h4>
Si j'utilise un h2 mais que je change la taille, c'est bon ? Parce qu'un h2 ou même un h3, c'était trop gros selon moi

2020-11-05 09:17 UTC, Flichyn commented
Corrigé !

2020-11-05 09:27 UTC, Aurelie-F commented
c'est ok

2020-11-05 16:23 UTC, sblondeau approved these changes

2020-11-05 16:24 UTC, sblondeau commented on src/View/Category/index.html.twig
> +                            <h4 class="card-title text-center align-middle">{{ category.name }}</h4>
oui c'est ce qu'il faut faire, un h2 puis du style en CSS pour faire la taille que tu souhaties

2020-11-05 16:24 UTC, merged