Fixed size for links and added link for 'Nos vélos'
WildCodeSchool/orleans-php-202009-project-dfj-location pull request #56
Opened 2020-11-04 15:37 UTC by Flichyn

2020-11-04 15:38 UTC, Aurelie-F reviewed
c'est ok

2020-11-04 19:25 UTC, sblondeau requested changes

2020-11-04 19:25 UTC, sblondeau commented on src/View/includes/_navbar.html.twig
> +                <a class="nav-link" href="/Home/index"><h4>Accueil</h4><span class="sr-only">(current)</span></a>
pourquoi un h4 ? tu n'en a pas besoin. ce n'est pas un titre ici, juste une entrée de navbar
utilise du CSS pour styliser ton lien et enlève le h4

2020-11-05 09:36 UTC, Flichyn commented
Corrigé !

2020-11-05 09:37 UTC, Aurelie-F commented
c'est ok

2020-11-05 11:12 UTC, Aurelie-F commented
ajout ok

2020-11-05 16:24 UTC, sblondeau approved these changes

2020-11-05 16:25 UTC, merged