finished US_21
WildCodeSchool/orleans-php-202009-project-dfj-location pull request #57
Opened 2020-11-04 16:06 UTC by AliNedjar

Finished the "nouveautés" part and asking for a review

2020-11-05 09:26 UTC, Aurelie-F reviewed
c'est ok

2020-11-05 16:29 UTC, sblondeau requested changes

2020-11-05 16:29 UTC, sblondeau commented on public/assets/css/style.css
> +.nouveautés h2 {
pas d'accent dans les noms de classe, en fait elles doivent etre en anglais !

2020-11-05 16:29 UTC, sblondeau commented on src/Model/HomeManager.php
> +            ' ORDER BY created_date DESC LIMIT 4 ')->fetchAll();
une bonne pratique, plutot que de mettre "4" en dur, est de faire plutot une constante, par ex BIKE_LIMIT dans la classe, c'est plus simple si besoin de faire évoluer cette limite par la suite

2020-11-05 18:27 UTC, Aurelie-F approved these changes
c'est ok

2020-11-06 07:57 UTC, sblondeau approved these changes

2020-11-06 07:57 UTC, merged