S03 us08 admin reservation
WildCodeSchool/orleans-php-202009-project-dfj-location pull request #89
Opened 2020-11-11 11:20 UTC by Aurelie-F

2020-11-12 09:26 UTC, AliNedjar approved these changes
tout m'a l'air okay!

2020-11-12 10:53 UTC, Flichyn approved these changes

2020-11-12 13:51 UTC, sblondeau requested changes
la PR ne passe pas sur Github Action

2020-11-12 13:51 UTC, sblondeau commented on src/Model/ReservationManager.php
> +        $statement = $this->pdo->prepare("UPDATE " . self::TABLE . " SET is_validated = 'OK' WHERE id=:id");
travaille plutot avec un booléen true ou false plutot que OK et KO

2020-11-12 13:51 UTC, sblondeau commented on src/Controller/AdminReservationController.php
> +            if ($data['action'] == 'Accepter') {
a retravailler, on en discute

2020-11-12 15:35 UTC, AliNedjar approved these changes
tout m'a l'air ok!

2020-11-12 20:06 UTC, sblondeau approved these changes

2020-11-13 08:04 UTC, AliNedjar approved these changes
les conflits sont réglés

2020-11-13 08:07 UTC, merged