first commit of US
WildCodeSchool/orleans-php-202009-project-dfj-location pull request #92
Opened 2020-11-12 14:55 UTC by AliNedjar

2020-11-12 18:22 UTC, Flichyn requested changes

2020-11-12 18:22 UTC, Flichyn commented on src/Controller/AdminCategoryController.php
> +        return $this->twig->render('Admin/indexcategory.html.twig', [ 'categories' => $categories]);
Il manque une majuscule sur le nom de ton fichier (indexCategory) et il y a un espace en trop entre ton crochet et 'categories'

2020-11-12 18:22 UTC, Flichyn commented on src/View/Admin/indexcategory.html.twig
> +
Lignes vides en trop

2020-11-13 08:22 UTC, Flichyn approved these changes

2020-11-13 08:56 UTC, sblondeau requested changes

2020-11-13 08:56 UTC, sblondeau commented on src/View/Admin/indexCategory.html.twig
> +                    <a href="{{ category.id }}" title="supprimer" class="btn btn-danger">
de ce que je vois, y a qu'une icone dans le bouton.
il faut mettre aussi un label, donc icone + texte, jamais l'icone seule

2020-11-13 09:15 UTC, AliNedjar commented on src/View/Admin/indexCategory.html.twig
> +                    <a href="{{ category.id }}" title="supprimer" class="btn btn-danger">
C'est les boutons supprimer et ajouter, qui sont dans la colonne Action, et y'a un title dessus donc ça se verra tout de suite pour ce qui est de l'action à utiliser et j'essaye de rester cohérent avec les autres parties administrateur, si je met un label ici, il faudrait en mettre sur les autres.

2020-11-15 13:09 UTC, bloic approved these changes
C'est ok pour moi :)

2020-11-16 08:00 UTC, sblondeau approved these changes

2020-11-16 08:01 UTC, merged